csv: "/Users/marcobarbacci/2D-Reactor/2D_Reactor/datasets/vae_params.csv"
save_model: "/Users/marcobarbacci/2D-Reactor/2D_Reactor/VAE/Weights/vae_model.pt"
latent_dim: 1
hidden_dims: [128, 128, 64]
dropout: 0.05
use_layernorm: true
out_activation: sigmoid
epochs: 100
batch_size: 64
lr: 0.001
beta: 1.0
